// <auto-generated />
using Festivo.Infraestructura.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Festivo.Infraestructura.Persistencia.Migrations
{
    [DbContext(typeof(FestivoContext))]
    partial class FestivoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Festivo.Dominio.Entidades.Feestivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("Dia");

                    b.Property<int?>("DiasPascua")
                        .HasColumnType("int")
                        .HasColumnName("DiasPascua");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("Mes");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.HasIndex("Nombre");

                    b.ToTable("Festivo");
                });

            modelBuilder.Entity("Festivo.Dominio.Entidades.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("Festivo.Dominio.Entidades.Feestivo", b =>
                {
                    b.HasOne("Festivo.Dominio.Entidades.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });
#pragma warning restore 612, 618
        }
    }
}
